### ISSUE TITLE
build error: ARM tool chain

### ISSUE THREAD

**Issue by harielamadu** [uctools/tiva-template#11]
Hi all,
 I have installed the development toolchain  for TI TIVA series as per the instructions given in the following page [https://github.com/uctools/tiva-template]  and while building the firmware using 'make' it prompts a fatal error 
![buiderror](https://user-images.githubusercontent.com/42768457/52783991-ae99c580-3079-11e9-9d65-3bc2fdb4c3d3.png)
help me to resolve this

**Comment by GamalOthman** [comment]
I have the same issue. There is `#include "inc/hw_types.h"` and there is now **inc** folder in **src** folder, so the compiler cannot continue.

**Comment by GamalOthman** [comment]
@harielamadu So, I tried some things and thankfully it worked! I don't know exactly what it made it work, but I will list the changes I made after writing my previous comment.
Things I changed is:-
1- I was naming the folder **TivaWare** so I changed it to **tivaware**, I also changed it in the **Makefile**
2- I changed the path to **tivaware** in **Makefile** to this form: _$(HOME)/Embedded/tivaware_
hope this will work for you!
